services:
  - type: web
    name: spotter-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: ORS_API_KEY
        value: "paste_your_key_here"
      - key: SECRET_KEY
        generateValue: true
